language: php
php:
- 5.5
install:
- ./composer install
- sudo pip install awscli; fi
script:
- ./scripts/deploy-s3.sh $TRAVIS_BRANCH
env:
  global:
  # AWS keys (encrypted)
  - secure: Y9SpHQkQXGHvQelzMfzNODU+hGkoStDfADnUQ11WlGNHdKA1sAy2xRg7Y/lAaqcIT1aF7EPk4G1nRFDPR8RLEJCGMEhKsXta0zuKq+yKJQX2TwnPzTeIVej9CJxkiFWeLIHmP8WQm5b/HEpE3g1UBWjibUI00HSUCZMeU/MSxnI=
  - secure: GjJAAhmwKpQPVH801yud08z9IaH5cAGkL4Dp0wFDD186olr0bgX+UIeK+nTLugl9DmyGIYfWnWMQSMXoUqAEj/Phm2ddOgYTIca8LkmDrwr7XBRIU0SPTrtHbRnpw3bpkAxuOIdasrinsB17VQe346DPZEkCbl53bVRnhRW1PSI=
